/**
 * Generated by scripts/db-tools/generate-types-from-pg.js
**/
declare namespace SqlSchema {
  export interface schema_migrations {
    created_at: Date | null
    hash: string | null
    name: string
  }
  
  export interface test_record {
    id: number
    name: string | null
  }
  
  export interface Schema {
    schema_migrations: schema_migrations
    test_record: test_record
  }
}
