name: Node.js Package

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    container: node:22
    services:
      postgres:
        image: postgres:11.6-alpine
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run check:all
      - run: npm run build
      - run: npm run test
        env:
          PGHOST: postgres
